#!/bin/bash

. ./config

if [[ $HOST == $localhost ]]; then
	export HOST=$LOOPBACK
else
	echo Host is safe, continuing
fi

if [[ $1 = "reset" ]]; then
	rm -rf data/
	mkdir data

elif [[ $1 = "sql-print" ]]; then
	mysql --password=$PASSWORD --user=$USER -B -e"SELECT sid,ip,port,rcon FROM sb_servers" $DATABASE > servers.csv
	cat servers.csv

elif [[ $1 = "details" ]]; then
	read -p "Please choose the ID (1/2/3/4) " DETAILS_ID
	echo "Hostname: $(ls data/ID"$DETAILS_ID"_* | sed -e "s/ID"$DETAILS_ID"_//g" | sed -e "s/data\///g" | sed -e "s/.log//g")"
	echo "Time     Date       Players"
	cat data/ID"$DETAILS_ID"_*

elif [[ $1 = "help" ]]; then
	echo "Welcome to the help page of Playercounts by Forefront!"
	echo "The version is: $VERSION"
	echo "	To start new, do \"./playercounts reset\"."
	echo "	To only print raw SQL data, do \"./playercounts sql-print\"."
	echo "	To print logs, do \"./playercounts details\"."
	echo "	To log playercounts, do \"./playercounts\"."
	echo "	To open this help menu, do \"./playercounts help\"."
	echo ""

else
	echo "Refer to \"./playercounts help\" for usage and information."
	touch cache
	
	mysql --password=$PASSWORD --user=$USER -B -e"SELECT sid,ip,port,rcon FROM sb_servers" $DATABASE > servers.csv

	for arg in ${ID[*]}; do
	   IP=$(grep -w "$arg" servers.csv | awk '{print $2}')
	   PORT=$(grep -w "$arg" servers.csv | awk '{print $3}')
	   RCON=$(grep -w "$arg" servers.csv | awk '{print $4}')
	   ./rcon -P $RCON -H $IP -p $PORT status | grep -e "players :" -e "hostname:" >> cache
	done
	
	# Sadly hardcoded to 4 servers as of right now

	SV1=$(cat cache | sed -n 2p | awk '{print $3}')
	SV2=$(cat cache | sed -n 4p | awk '{print $3}')
	SV3=$(cat cache | sed -n 6p | awk '{print $3}')
	SV4=$(cat cache | sed -n 8p | awk '{print $3}')
		
	NAME1=$(cat cache | sed -n 1p | sed -e 's/hostname: 「MODDAGE」x1,000,000 //g')
	NAME2=$(cat cache | sed -n 3p | sed -e 's/hostname: 「MODDAGE」x1,000,000 //g')
	NAME3=$(cat cache | sed -n 5p | sed -e 's/hostname: 「MODDAGE」x1,000,000 //g')
	NAME4=$(cat cache | sed -n 7p | sed -e 's/hostname: 「MODDAGE」x1,000,000 //g')
	
	echo "$TIME $SV1" >> data/ID1_"$NAME1.log"
	echo "$TIME $SV2" >> data/ID2_"$NAME2.log"
	echo "$TIME $SV3" >> data/ID3_"$NAME3.log"
	echo "$TIME $SV4" >> data/ID4_"$NAME4.log"

	rm cache
fi